version: '3.4'

services:
  bancosanguemvc:
    image: ${DOCKER_REGISTRY-}BancoDeSangue
    build:
      context: .
      dockerfile: .
    ports:
     - "8081:80"       
    depends_on:
     - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=BcoSague#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data   
    ports:
      - "1450:1433"  